version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:      
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis_db
    